#!/usr/bin/env bash
# Script that install Nginx Web Server

sudo apt-get update
sudo apt-get install nginx -y
sudo /etc/init.d/nginx start
sudo chmod 757 /var/www/html/index.nginx-debian.html
sudo echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo chmod 755 /var/www/html/index.nginx-debian.html
