#!/usr/bin/env bash
# Script that install Nginx Web Server

sudo apt-get update
sudo apt-get install nginx -y
sudo /etc/init.d/nginx start
sudo chmod 777 /var/www/html
sudo echo "Holberton School" > /var/www/html/index.nginx-debian.html
