#!/usr/bin/env bash
# This script configurate enable sites to listen 80 and not 8080 port

cd /etc/nginx/sites-enabled
sudo sed -i 's/listen 8080/listen 80' default
sudo sed -i 's/8080 default_server ipv6only=on;/80 default_server ipv6only=on;/' default
sudo service nginx restart
