#!/usr/bin/env bash
# This script prints a task 10 times and use an if condition

i=1
li=9
str='Holberton School'

while [ $i -le 10 ]
do
	if [ "$i" == $li ]; then echo "HI"; else echo "$str"; fi
	(( i++ ))
done
