#!/usr/bin/env bash
# This scrip producs the hours for half day

i=0
j=1

while [ $i -le 12 ]; do
	echo "Hour: $i"

	while [ $j -lt 60 ]; do
		echo "$j"
		(( j++ ))
	done
	if [ "$j" -eq 59 ]; then
		echo "Hour: $i"
		(( j=0 ))
	fi
	(( i++ ))
done
