#!/usr/bin/env bash
# This script verificate states for a file

device="/home/vagrant/holberton-system_engineering-devops/0x04-loops_conditions_and_parsing/holbertonschool"

if [ -e "$device" ]; then
	echo "holbertonschool file exist"

	if [ -s "$device" ]; then
		echo "holbertonschool file is not empty"
	else
                echo "holbertonschool file is emtpy"
	fi

	if [ -f "$device" ]; then
		echo "holbertonschool is a regular file"
	fi
else
	echo "holbertonschool file does not exist"
		
fi
