#!/usr/bin/env bash
# This script verificate states for a file

device=holbertonschool

if [ -e $device ]; then
	echo "holbertonschool file exists"

	if [ -s $device ]; then
		echo "holbertonschool file is not empty"
	fi
	if [ ! -s $device ]; then 
                echo "holbertonschool file is emtpy"
	fi
	if [ -f $device ]; then
		echo "holbertonschool is a regular file"
	fi
else
	echo "holbertonschool file does not exist"
fi
